import dataclasses as dc
import numpy as np
import numpy.random as random

from a_package.data_record import *


def test_save_load():
    eta = 0.01
    n_grid = 200

    test_data = DropletData(
        V = 1e6 * eta**3,
        eta = eta,
        L = n_grid * eta,
        M = n_grid,
        N = n_grid,
        phi = random.rand(n_grid, n_grid),
        h1 = random.rand(n_grid, n_grid),
        h2 = random.rand(n_grid, n_grid),
        d = 2 * eta,
        x = np.arange(n_grid) * eta,
        y = np.arange(n_grid) * eta,
        dx = eta,
        dy = eta,
    )

    test_record = Record(
        data = [test_data],
        init_guess = random.rand(n_grid, n_grid),
    )

    filepath = "this is generated by test.data"
    save_record(test_record, filepath)

    loaded_test_record = load_record(filepath)
    [loaded_test_data] = loaded_test_record.data

    for field in dc.fields(DropletData):
        loaded_value = getattr(loaded_test_data, field.name)
        saved_value = getattr(test_data, field.name)
        assert np.all(loaded_value == saved_value), "The loaded data is not the same as the saved."


if __name__ == '__main__':
    test_save_load()
